# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 09:15
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('department', models.CharField(choices=[('Other', 'Autres'), ('Axes', 'Axes'), ('Frames', 'Cadres'), ('Bars', 'Ceintres'), ('Chains', 'Chaines'), ('Forks', 'Fourches'), ('Pedals', 'Pedales'), ('Pedaliers', 'Pedaliers'), ('Tires', 'Pneus'), ('Potences', 'Potences'), ('Wheels', 'Roues'), ('Saddles', 'Selles'), ('Bikes', 'Velos')], default='Other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock.Article')),
                ('quantity', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
