# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name, Prenom, Nombre', max_length=40)),
                ('last_name', models.CharField(help_text='Family name, Nom, Apellidos', max_length=40)),
                ('email', models.EmailField(help_text='Enter email like exemple@domain.com', max_length=100, unique=True)),
                ('active_member', models.BooleanField(default=False, help_text='Do you want to become an active member? :)')),
            ],
        ),
    ]
